const API_BASE = window.DC_ADS_API_BASE || "";
const $ = id => document.getElementById(id);
const esc = s => String(s ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

function showPayment(message,error=false){const box=$("payment");box.classList.remove("hidden");box.style.borderColor=error?"#d94b4b":"";box.innerHTML=message;box.scrollIntoView({behavior:"smooth",block:"center"});}
async function api(path,options={}){if(!API_BASE)throw new Error("Backend is not connected. GitHub Pages only hosts the website; server.py must be deployed separately.");const r=await fetch(API_BASE.replace(/\/$/,"")+path,options);const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text||`HTTP ${r.status}`}}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d}
async function loadAds(){try{const d=await api("/api/ads");renderAds(Array.isArray(d)?d:[])}catch(e){renderAds([]);console.warn(e.message)}}
function renderAds(ads){const q=$("searchBox").value.toLowerCase().trim();const a=ads.filter(x=>[x.business,x.player,x.category,x.location,x.text].join(" ").toLowerCase().includes(q));$("adCount").textContent=`(${a.length} live)`;const html=a.map(x=>`<article class="card"><span class="tag">${esc(x.category)}</span><h3>${esc(x.business)}</h3><div class="meta">👤 ${esc(x.player)} ${x.location?"· 📍 "+esc(x.location):""}</div><p>${esc(x.text)}</p></article>`).join("");$("liveAds").innerHTML=html;$("results").innerHTML=html}
$("searchBox").addEventListener("input",loadAds);
$("adForm").addEventListener("submit",async e=>{e.preventDefault();const plan=document.querySelector('input[name="plan"]:checked').value;const payload={business:$("business").value.trim(),player:$("player").value.trim(),category:$("category").value,location:$("location").value.trim(),text:$("adText").value.trim(),plan};showPayment("<b>⏳ CREATING PAYMENT REQUEST...</b>");try{const d=await api("/api/ads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});showPayment(`<b>💰 PAYMENT REQUIRED</b><p>Send <b>DC$${esc(d.price)}</b> to advertising account <code>${esc(d.paymentAccountId)}</code>.</p><p>Reference: <code>${esc(d.paymentReference)}</code></p><button class="pixel-btn" id="check" type="button">CHECK PAYMENT</button><p id="status"></p>`);$("check").addEventListener("click",()=>checkPayment(d.adId))}catch(err){showPayment(`<b>⚠️ PAYMENT SETUP ERROR</b><p>${esc(err.message)}</p>`,true)}});
async function checkPayment(id){const s=$("status");s.textContent="⏳ Checking DemocracyCraft Treasury...";try{const d=await api(`/api/ads/${encodeURIComponent(id)}/status`);if(d.status==="active"){s.textContent="✅ Payment confirmed — your ad is LIVE.";loadAds()}else if(d.status==="pending_payment")s.textContent="⏳ Payment has not been detected yet.";else s.textContent=`⚠️ ${d.status}`}catch(e){s.textContent=`⚠️ ${e.message}`}}
loadAds();